default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "app_test") %>
  username: <%= ENV["CI"] ? "postgres" : ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV["CI"] ? "password" : ENV.fetch("POSTGRES_PASSWORD", "") %>
  host: <%= ENV["CI"] ? "localhost" : ENV.fetch("POSTGRES_HOST", "localhost") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "app_development") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "app_production") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "app") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
