default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", File.exist?("/.dockerenv") ? "db" : "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", File.exist?("/.dockerenv") ? "postgres" : "") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

test:
  <<: *default
  # POSTGRES_DB は開発用(default: app_development)と共有されがちなので分離する
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "app_test") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "app_development") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "app_production") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "app") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
